
apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-frontend
  namespace: student-management

spec:
  replicas: 3

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: nginx
          image: nginx:latest

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: APP_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: student-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-secret
                  key: DB_PASSWORD

            
