apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-yaml
  name: pod-yaml
spec:
  containers:
  - image: nginx
    name: pod-yaml
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
