apiVersion: v1
kind: Pod
metadata:
  name: special-workload

spec:
  nodeSelector:
    dedicated: special

  tolerations:
    - key: dedicated
      operator: Equal
      value: special
      effect: NoSchedule

  containers:
    - name: nginx
      image: nginx
