apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: node-monitor
  namespace: kube-system

spec:
  selector:
    matchLabels:
      app: node-monitor

  updateStrategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: node-monitor

    spec:

      nodeSelector:
        monitoring: "true"

      
      tolerations:
        - operator: Exists

      containers:
        - name: node-monitor
          image: busybox:1.37

          command:
            - /bin/sh
            - -c
            - |
              echo "Node monitoring agent started"
              while true; do
                echo "Monitoring node..."
                sleep 30
              done

          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
