apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs-production.fullname" . }}
  labels:
    {{- include "nodejs-production.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  NODE_ENV: {{ .Values.config.environment | quote }}
