apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejs-production.fullname" . }}
  labels:
    {{- include "nodejs-production.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}
