apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodejs-production.fullname" . }}
  labels:
    {{- include "nodejs-production.labels" . | nindent 4 }}
automountServiceAccountToken: true
