apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "nodejs-production.fullname" . }}-test"
  labels:
    {{- include "nodejs-production.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox:1.36
      command:
        - wget
        - -qO-
        - "http://{{ include "nodejs-production.fullname" . }}:{{ .Values.service.port }}/health"
